### ISSUE TITLE
deluged fails to start (but deluge-web runs)

### ISSUE THREAD

**Issue by hexadecagram** [jsegaert/iocage-plugin-deluge-pip#13]
Plugin version: 14.2.0.6
Jail Release version: 13.1-RELEASE-p9
TrueNAS version: 13.0-U4

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 21, in <module>
    import deluge.libtorrent as lt
ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 24, in <module>
    import libtorrent as lt
ModuleNotFoundError: No module named 'libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/deluged", line 8, in <module>
    sys.exit(start_daemon())
  File "/usr/local/lib/python3.9/site-packages/deluge/core/daemon_entry.py", line 87, in start_da
emon
    from deluge.core.daemon import is_daemon_running
  File "/usr/local/lib/python3.9/site-packages/deluge/core/daemon.py", line 19, in <module>
    from deluge.core.core import Core
  File "/usr/local/lib/python3.9/site-packages/deluge/core/core.py", line 26, in <module>
    from deluge._libtorrent import LT_VERSION, lt
  File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 26, in <module>
    raise LibtorrentImportError('No libtorrent library found: %s' % (ex))
deluge.error.LibtorrentImportError: No libtorrent library found: No module named 'libtorrent'
```

**Comment by hexadecagram** [comment]
Looks like this is related to #11.

**Comment by mihawk90** [comment]
Just came across the same issue during the first install.

From what I'm reading in the Post-Install log it is indeed still an issue with `py-libtorrent-rasterbar`:

[deluge_install.log](https://github.com/jsegaert/iocage-plugin-deluge-pip/files/12798890/deluge_install.log)

```
Building new INDEX files... done.

102 MB 50 MBps 02s

A py-libtorrent-rasterbar/files

102 MB 50 MBps 02s

A py-libtorrent-rasterbar/Makefile

102 MB 50 MBps 02s

A py-libtorrent-rasterbar/distinfo

102 MB 50 MBps 02s

A py-libtorrent-rasterbar/files/b2

102 MB 50 MBps 02s

A py-libtorrent-rasterbar/files/patch-ca9a7f3b89095949e30f533e53080293f33f2f60

102 MB 50 MBps 02s

A py-libtorrent-rasterbar/pkg-descr

102 MB 50 MBps 02s

Checked out revision 569235.

102 MB 50 MBps 02s

You should be done-- now cd into py-libtorrent-rasterbar and you can run

# make deinstall install clean

Please note that portdowngrade no longer modifies the ports tree; the

checked out port is at

/root/py-libtorrent-rasterbar

102 MB 50 MBps 02s

===> Deinstalling for py39-libtorrent-rasterbar

102 MB 50 MBps 02s

===> py39-libtorrent-rasterbar not installed, skipping

102 MB 50 MBps 02s

/!\ ERROR: /!\

102 MB 50 MBps 02s

102 MB 50 MBps 02s

Ports Collection support for your FreeBSD version has ended, and no ports are

guaranteed to build on this system. Please upgrade to a supported release.

102 MB 50 MBps 02s

102 MB 50 MBps 02s

No support will be provided if you silence this message by defining

ALLOW_UNSUPPORTED_SYSTEM.

102 MB 50 MBps 02s

102 MB 50 MBps 02s

*** Error code 1

Stop.

make: stopped in /root/py-libtorrent-rasterbar

102 MB 50 MBps 02s

deluged_enable: -> YES

102 MB 50 MBps 02s

deluged_user: -> deluge

102 MB 50 MBps 02s

deluge_web_enable: -> YES

102 MB 50 MBps 02s

deluge_web_user: -> deluge

102 MB 50 MBps 02s

Starting deluged.

102 MB 50 MBps 02s

Starting deluge_web.

102 MB 50 MBps 02s

Starting deluge_web.

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 21, in

Starting deluge_web.

import deluge.libtorrent as lt

ModuleNotFoundError: No module named 'deluge.libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 24, in

import libtorrent as lt

ModuleNotFoundError: No module named 'libtorrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):

File "/usr/local/bin/deluged", line 8, in

sys.exit(start_daemon())

File "/usr/local/lib/python3.9/site-packages/deluge/core/daemon_entry.py", line 87, in start_daemon

from deluge.core.daemon import is_daemon_running

File "/usr/local/lib/python3.9/site-packages/deluge/core/daemon.py", line 19, in

from deluge.core.core import Core

File "/usr/local/lib/python3.9/site-packages/deluge/core/core.py", line 26, in

from deluge._libtorrent import LT_VERSION, lt

File "/usr/local/lib/python3.9/site-packages/deluge/_libtorrent.py", line 26, in

raise LibtorrentImportError('No libtorrent library found: %s' % (ex))

deluge.error.LibtorrentImportError: No libtorrent library found: No module named 'libtorrent'
```

Do you know of any issue being filed upstream for this to potentially be resolved? Bit of a bummer this is the first thing I run into on a new setup :sweat_smile:

**Comment by cscorley** [comment]
Looks like the package is currently stable, so I was able to fix this by installing the package (1.2.19,2) instead of building from ports (as post_install does):

```
pkg install py39-libtorrent-rasterbar
services deluged start
```

Hope that helps someone!

**Comment by jsegaert** [comment]
Thanks for your message.  Yeah, installing from pkg is ideal.  The only reason I created this iocage-plugin-deluge-pip plugin in the time, was to act as a workaround & band-aid because the original iocage-plugin-deluge plugin was broken more often than not.

iXsystems annouced they will stop supporting these iocage-based plugins in TrueNAS CORE in the next major release, but it's easy enough to just to create a jail and install deluge from pkg.
