### ISSUE TITLE
Deluged service not starting

### ISSUE THREAD

**Issue by aserrallerios** [jsegaert/iocage-plugin-deluge-pip#7]
Brand new jail created today. Service doesn't start, if I try to do it manually I get this:
```
root@deluge-pip:~ # service deluged start
\Starting deluged.
Traceback (most recent call last):
  File "/usr/local/bin/deluged", line 8, in <module>
    sys.exit(start_daemon())
  File "/usr/local/lib/python3.8/site-packages/deluge/core/daemon_entry.py", line 87, in start_daemon
    options = parser.parse_args()
  File "/usr/local/lib/python3.8/site-packages/deluge/argparserbase.py", line 250, in parse_args
root@deluge-pip:~ # \    return self._handle_ui_options(options)
  File "/usr/local/lib/python3.8/site-packages/deluge/argparserbase.py", line 329, in _handle_ui_options
    _file.write('%d\n' % os.getpid())
TypeError: a bytes-like object is required, not 'str'
```

**Comment by raidoz** [comment]
The plugin install script does patches some deluge code, however, does not specify a version when installing deluge, therefore it now gets a version that is no longer compatible with the patches. It seems both patches have already been integrated into 2.0.5, which is what gets installed currently. So the patching step should be removed now. As a workaround, enter the shell of the jail and run `pip3 uninstall deluge` and `pip3 install deluge` and restart the jail.

**Comment by jsegaert** [comment]
Thank you!  I removed the patches from the post_install script, and that seemed to fix it.
